### ISSUE TITLE
Homepage: Mobile view

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#3]
On mobile, align items to center. On full screen, align left.

**Comment by joshyide** [comment]
Hi @jlooper I'm looking to make my first contributions to open source / for Hacktoberfest.
I'd be happy to take this (and maybe some other issues) if you would like to assign me?

Of course I understand Front-End Foxes is about providing opportunities to women, so if somebody else comes along who'd like to take the issue or you'd like to offer it to somebody else, more than happy to step aside and let somebody else take it.

Otherwise, happy to contribute!

**Comment by jlooper** [comment]
Thank you, Joshua! All contributions are extremely welcome! Happy to let you take this one! 😎🦊😎🦊
