### ISSUE TITLE
QA for French translations

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#30]
Let's QA the upcoming French version of this web site

**Comment by Tititesouris** [comment]
Hi @jlooper, just to be clear, this issue is about going through the French translations and look for mistakes? I have had a look and it looks like there are a lot of Google-Translate quality texts in there, so I would offer quite a few changes.
If that's the case, let me know and I'll get working on it

**Comment by jlooper** [comment]
Hi! Yes, many translations are placeholders and need to be redone. Thank you!

**Comment by Tititesouris** [comment]
Perfect, then I'll be working on that throughout next week :)

**Comment by jlooper** [comment]
Merci!!!

**Comment by Tititesouris** [comment]
Here's what I worked on so far, I will see if I find time to work on more #56
