### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/ff-web#9]
Use the mitt package to add localizations (pattern is at https://github.com/jlooper/static-game-engine/blob/master/app/package.json) to enable localizations. Use our old system on frontendfoxes.org to have a flag appear in the top right corner with a dropdown to change localization.

**Comment by nicoletteschreier** [comment]
I would love to work on this

**Comment by jlooper** [comment]
Please do! This is a big job but i18n with translations.js files should do the trick! Thanks!

**Comment by nicoletteschreier** [comment]
I am super new to this. I think I misunderstood what I was signing up for, and do not fully understand the ask. Could you explain this a little more?

**Comment by jlooper** [comment]
Hi, a full site translation is not an easy first contribution... you'll need to install a plug-in to make it work and then all hard coded strings need to be translated, with translations stored in separate folders. It's a pretty big job - previously we had it done - it's in our /website repo

**Comment by jlooper** [comment]
Also hello, Progress! 😍

**Comment by nicoletteschreier** [comment]
If someone else wants to take this up feel free, and I can learn from what you do. I am going to give this a try but not sure I could complete the whole thing.

**Comment by ansidev** [comment]
@jlooper Why would you use mitt? Currently, I am using `vue-i18n`.

**Comment by jlooper** [comment]
Hi, you'll need mitt to allow the localization drop down to refresh the page, paired with i18n - previously we used EventBus for the refresh but it's deprecated in Vue 3. 

I created a branch for this work as it's kind of big

**Comment by alxmcr** [comment]
Hi!

I have no idea, someone still working with it. In any case,  I was working with the translations (English and Spanish) on some pages (Home and Sponsors). This is the [result](https://ff-localizations.netlify.app/). I don't know if it is expected. Could you please review it? 🙏 I'll appreciate it.

I needed some changes to the base code:
- Updated "vue-i18n" dependency to "vue-i18n@next", because "vue-i18n" isn't ready yet to Vue 3 (I read some issues), because I have problems with the previous version.
- Added a "new idea" to organize the translations and change .js to .json.
- Added some language flags on the header to change the languages.

What do you think about these changes? Maybe, there are better solutions, it's only my suggestion.

Thanks!

Note.- If it's OK, I still need review sentences, grammar, etc., and I have to think about how we can apply some translation on iterate data and complete all translations.

**Comment by jlooper** [comment]
hi! Wow, this is looking very promising! 

I am hoping that we can port over all the translations we did here: 
https://github.com/FrontEndFoxes/website/tree/main/assets/translations

and use "flag-icon-css": as per the old package.json, if we can, as a flag dropdown

I think we should do these translations on branches, so that we can get reviewers to QA them (Spanish/Portuguese/French/Japanese to start - I don't think we need to differentiate pt-br from pt; and I want an American flag for English :) - small details ). I will ask our Japanese chapter to take a look at adding Japanese translations.

Here's the code for the actual dropdown: here's where we need mitt to help with page refresh, looks like you got that working!!

https://github.com/FrontEndFoxes/website/commit/f8653a13cee0d08c135d80b5a92632b489323cff#diff-2bf98384263cf7fd15d9de005781efbe (this was the moment we removed them as it was hard to maintain)

**Comment by alxmcr** [comment]
> I am hoping that we can port over all the translations we did here

Hi!

**Great ideas and corrections!** Thank you so much! I'll apply them.

- About the translations, yes I used some values from the **translations** folder, but I've applied a different folder structure:

```
src
|___ i18n/
       |____ en/
                 |____ en-header.json
                 |____ en-home.json
                 |____ en-footer.json
                 |____ ...
       |____ es/
                 |____ es-header.json
                 |____ es-home.json
                 |____ es-footer.json
                 |____ ...
```
    
I think It can be a little more organized, and maybe maintainable because you could organize the **Translation Reviewer teams** in the future easily. 

For example: 
- English team -> **/en**
- Spanish team -> **/es**
- Japan team -> **/jp**
- etc. 

But, I can **change** to the original idea., No problem. **What do you think about it?**

Thanks!

**Note.-** I still have to think about how we can apply some translations on **iterate or dynamic data. Please, if you have some ideas, I'll appreciate it** Also, I have to complete all missing translations.

**Comment by jlooper** [comment]
I like your organization idea, it's better than longer and longer translation files! nice one!

I think you're wondering about the translations for the .json data, like the .json files for Event Gallery. Hmm. One thing I was thinking is not bothering translating those, as they are just event names which won't have a translation and the city/country can stay per se. I think this will be more maintainable, as every time I add an event I'd potentially have to add translations to three or four different files, it's not worth it. I think it's ok to translate the important parts of the site (H1 headers and the About page, mostly, and the home page). 

Does that sound right to you?

Thank you again!!

**Comment by alxmcr** [comment]
> I like your organization idea, it's better than longer and longer translation files! nice one!
> 
> I think you're wondering about the translations for the .json data, like the .json files for Event Gallery. Hmm. One thing I was thinking is not bothering translating those, as they are just event names which won't have a translation and the city/country can stay per se. I think this will be more maintainable, as every time I add an event I'd potentially have to add translations to three or four different files, it's not worth it. I think it's ok to translate the important parts of the site (H1 headers and the About page, mostly, and the home page).
> 
> Does that sound right to you?
> 
> Thank you again!!

Hi!

Good news! I was working the translations. I believe that happily more sections are translated such as cards, it's amazing to me!!!. 

Example: Spanish translations are **95%**, it's possible there are **some mistakes.** But, I think the most important thing is done. How do we change between languages?. 

Now, we can choose between **four languages**: English, Spanish, French, and Portuguese.

**Could you please review this [new version](https://i18n-ff.netlify.app)? I'll appreciate it.** 🙏🙏

I feel that we're near to finish this issue. But, I'm **open** to new ideas, corrections, improvements, etc. **I'm happy!!!** 😄😄😄

**Thanks!**

Note.- I think that we'll need help to **support other languages**, and QA to **review our translations**, because my native language is Spanish, and I know a little English 😄  but I can try some translator. **What do you think?**

**Comment by jlooper** [comment]
this is wonderful, and the language dropdown works great! We might need to rely on our chapter leaders to correct our translations. I'm just not sure about the Portuguese. Let me open some issues!

Really appreciate all this work!

**Comment by alxmcr** [comment]
Hi!

**Thanks for your words!**

Your page is more incredible and complete every day. **Congratulations!** 🥳 Many people did many amazing **contributions**. Thanks! it's great!

Do you think this version is ready for **some pull request** and more people can **contribute or review** the translations? Which **branch** should you use? or do you have some additional comments or suggestions?

Thanks!

**Note.-** There are many changes to base code 😄

**Comment by jlooper** [comment]
hi, would you like to make a PR for the base code, and I think I'll make branches for each translation as we roll them in progressively. Let's start with English and Spanish committed to 'main' and I'll branches for French, Portuguese, and Japanese so we can enhance the site progressively. Many thanks again!

**Comment by alxmcr** [comment]
> hi, would you like to make a PR for the base code, and I think I'll make branches for each translation as we roll them in progressively. Let's start with English and Spanish committed to 'main' and I'll branches for French, Portuguese, and Japanese so we can enhance the site progressively. Many thanks again!

I'm so sorry for my delay with the PR 😔. I hadn't considered unit testing and the translations, incompatibility between versions, and other little details then I was learning about testing in Vue, Jest, reading documentation, blogs, websites, etc., and fixing some problems. This weekend was crazy and amazing. I've learned a lot and got great memories and experiences solving this issue.  Thanks! 😄

Also, I wrote a little **guide** to translations maintainers. I hope It's useful.

Fortunately, the **PR is now on Github**  🥳. I'm really happy. 😄

**Thanks for your time, support, and help! Have a nice day!**

**Comment by jlooper** [comment]
I have no words.... I'm just amazed by the amount of work here. Thank you so much, Alejandro!!! 🙏🙏🙏🙏🙏🙏🙏

Just amazed 🤗🤗🤗🤗🤗

**Comment by alxmcr** [comment]
Thanks for all! Your project is great and I'm really happy that I could help a little with it 😊.  It was **_teamwork_**, **thanks for your time, support, advice, and your help!**. It was incredible, amazing, and challenging but it helped me to learn new technologies, experiment with new tools, and know interesting things. 

**Thank you so much, Jen!** 😊

All the best, and **Congratulations on your amazing work!** 🥳 Have a nice day!
